[project]
name = "marimo-etl"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "altair",
    "marimo[recommended]",
    "numpy",
    "pandas",
    "polars",
    "quak",
    "seaborn",
]
