[project]
name = "marimo-etl"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "altair>=5.5.0",
    "marimo[recommended]>=0.11.20",
    "numpy>=2.2.3",
    "pandas>=2.2.3",
    "polars>=1.25.2",
]
